use std::{env, fs, path::PathBuf};

fn main() {
    println!("cargo:rerun-if-changed=src/types.rs");

    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let types_path = manifest_dir.join("src").join("types.rs");
    let types = fs::read_to_string(&types_path).unwrap();
    let type_names = collect_public_type_names(&types);

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let output_path = out_dir.join("roco_type_list.rs");
    fs::write(output_path, render_type_list(&type_names)).unwrap();
}

fn collect_public_type_names(source: &str) -> Vec<String> {
    source
        .lines()
        .filter_map(|line| {
            let trimmed = line.trim_start();
            let rest = trimmed
                .strip_prefix("pub struct ")
                .or_else(|| trimmed.strip_prefix("pub enum "))?;
            let name = rest
                .split(|ch: char| !(ch.is_ascii_alphanumeric() || ch == '_'))
                .next()?;
            if name.is_empty() {
                None
            } else {
                Some(name.to_string())
            }
        })
        .collect()
}

fn render_type_list(type_names: &[String]) -> String {
    let mut output = String::from(
        "// @generated by build.rs; do not edit.\n\
         macro_rules! for_each_roco_type {\n\
         \x20   ($macro:ident) => {\n",
    );

    for name in type_names {
        output.push_str(&format!(
            "        $macro!(crate::types::{name}, \"{name}\");\n"
        ));
    }

    output.push_str("    };\n}\n");
    output
}
